### ISSUE TITLE
Sponserblock sometimes loops endlessly.

### ISSUE THREAD

**Issue by UpFromTheShadows** [reisxd/TizenTube#27]
If a video starts with a sponsor (as many do) it endlessly loops and attempts to skip it, you canlcannot skip ahead (or as far as I am aware do anything other than watch the video on stock youtube). Sometimes this also occurs in sponsors that are in the middle of a video (I think it's to do with one sponsor being skipped leading into another) which also starts the endless loop.

**Comment by twsl** [comment]
I have the same issue

**Comment by cremor** [comment]
This might happen if the sponsor segment is too short to skip. See here for a related issue on the LG app and for more detail: https://github.com/webosbrew/youtube-webos/issues/148#issuecomment-2028788759

**Comment by cremor** [comment]
I don't think that this is fixed. I saw the endless loop with TizenTube 1.12.3 and TizenBrew 2.0.3 with this video, which also contains a short sponsor segment at the start: https://www.youtube.com/watch?v=nKkgEwxRE5Q

**Comment by BitGrub** [comment]
Can confirm this is still happening. Also skipping a segment that goes to the end of a video loops it instead of respecting the playlist/autoplay
